### ISSUE TITLE
can't cancel window close

### ISSUE THREAD

**Issue by pushkin-** [marb2000/DesktopWindow#8]
Canceling the window close doesn't work for me.

I'm doing:
```
this.Closing += MainWin_Closing;
private void MainWin_Closing(object sender, WindowClosingEventArgs e)
{
    if (someCondition())
	e.TryCancel();
}
```

When I click the X, the WM_CLOSE message is being intercepted by the `NewWindowProc` in DesktopWindow (at which point `IsClosing` is still `false`), so we call `OnClosing()` which then triggers my `MainWin_Closing` handler which then calls `TryCancel()` which sets `IsClosing` to `true`, but then we just exit.

What am I doing wrong?

**Comment by BestOwl** [comment]
You can use `AppWindow` from Windows App SDK

``` c#
// Retrieve the window handle (HWND) of the current (XAML) WinUI 3 window.
IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);

// Retrieve the WindowId that corresponds to hWnd.
WindowId windowId = Win32Interop.GetWindowIdFromWindow(hWnd);

// Lastly, retrieve the AppWindow for the current (XAML) WinUI 3 window.
AppWindow appWindow = AppWindow.GetFromWindowId(windowId);
appWindow.Closing += AppWindow_Closing;
```
``` c#
private void AppWindow_Closing(AppWindow sender, AppWindowClosingEventArgs args)
{
    args.Cancel = true;
}
```
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview

**Comment by pushkin-** [comment]
@BestOwl  Cool that works. I'm going to close this issue out since I think the workaround is preferable to the using DesktopWindow::OnClosing anyway.
